name: PR CI
on:
  pull_request:
    branches: [main]
jobs:
  ci:
    runs-on: self-hosted
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: framely/actions-feishu-bot-hook@v1
        with:
          hook-id: ${{ secrets.FEISHU_HOOK_ID }}
          github-token: ${{ secrets.PAT_TOKEN }}
      - uses: actions/checkout@v3
        with:
          submodules: "true"
          token: ${{ secrets.PAT_TOKEN }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - uses: framely/actions-composite-expand@main
        with:
          main: |
            python -m pip show pydantic
            bash -xe .ci.sh
